### ISSUE TITLE
Include symbolic link doesn't work on Windows

### ISSUE THREAD

**Issue by FalsinSoft** [igagis/agg#5]
Hi

This is not really an issue ot, at least, it's a partial issue. In this project you have a symbolic link inside the in "include" folder on root project. Other your projects that needs this library (like svgren) refer to the include file here as:

```
#	include <agg/agg_rendering_buffer.h>
#	include <agg/agg_pixfmt_rgba.h>
#	include <agg/agg_renderer_base.h>
```

than work on linux able to manage symbolic link but compilation fails on Windows cause the path is missing (pull git project doesn't produce the correct path). Do you think it would be possible to change folders structure by avoid the use of symbolic links?
Thank you

**Comment by igagis** [comment]
This symbolic link is needed for proper Maven packaging for Android. See this issue which would allow eliminating this symbolic link:
https://github.com/howardpang/androidNativeBundle/issues/7
but it is not resolved yet and seems unprioritized

**Comment by FalsinSoft** [comment]
Thank you. Actually it's not a big problem for me because I copy the source files according to my project structure. I had only reported the thing but if there is a specific reason for this choice then that's okay.

**Comment by igagis** [comment]
FYI: I removed the symlink, now the headers can be taken from `src/agg/include`
