### ISSUE TITLE
How to get correct results with Porter-Duff composition

### ISSUE THREAD

**Issue by thomasp85** [igagis/agg#6]
Hi

I apologise in advance if this question does not fit here. I don't know of others using AGG and as you know the main development stopped a long time ago so I'm taking a shot with this repo :-)

I'm maintaining and developing a set of graphic backends to R based on AGG (https://github.com/r-lib/ragg). I'm attempting to add support for various blend modes, and for most parts it works correctly using `agg::comp_op_adaptor_rgba_pre` and `agg::pixfmt_custom_blend_rgba`.

However, for the rendering operations that should modify the area outside of the polygon getting rasterised I do not get the correct result as that area is not touched during the scanline rendering. The composition operators this relates to are `agg::comp_op_src`, `agg::comp_op_src_in`, `agg::comp_op_src_out`, `agg::comp_op_dst`, `agg::comp_op_dst_over`, `agg::comp_op_dst_in`, and `agg::comp_op_dst_atop`. All of these requires the rendering buffer to be cleared outside of the areas touched by the scanline renderer.

Am I missing a scanline mode that scans the full buffer or is this a deficiency in AGG?

I hope you are able to help - thanks in advance

**Comment by igagis** [comment]
Hi Thomas,

Unfortunately, I'm not able to help with this, as I'm not that much familiar with AGG. I use AGG only for my SVG rasterizer https://github.com/cppfw/svgren, you can check the code there, but at first quick look I couldn find any use of `agg::comp_op_*`. And I haven't touched it for several years now, as `svgren` is more or less stable.
I think I'm not using any of the composition operators you mentioned there, that means I have no any experience with them.

Br,
Ivan

**Comment by thomasp85** [comment]
All good. Thanks for getting back to me
